/*
 MB91520 Series I/O register definition file V01L05
 ALL RIGHTS RESERVED, COPYRIGHT (C) FUJITSU SEMICONDUCTOR LIMITED 2011
 LICENSED MATERIAL - PROGRAM PROPERTY OF FUJITSU SEMICONDUCTOR LIMITED
*/
#ifndef WIN32
#define __IO_DEFINE
#endif
#include "_fr.h"
