#include "mb91520.h"

void __DI(void) {}
void __EI(void) {}
void __wait_nop(void) {}
void __set_il(int il)
{
    (void)il;
}
/*__IO_EXTENDED*/ IO_CLKG_STR	IO_CLKG;
/*__IO_EXTENDED*/
IO_CCTL_STR   IO_CCTL;
/*__IO_EXTERN*/
PDR00STR	IO_PDR00;
/*__IO_EXTERN*/
PDR01STR	IO_PDR01;
/*__IO_EXTERN*/
PDR02STR	IO_PDR02;
/*__IO_EXTERN*/
PDR03STR	IO_PDR03;
/*__IO_EXTERN*/
PDR04STR	IO_PDR04;
/*__IO_EXTERN*/
PDR05STR	IO_PDR05;
/*__IO_EXTERN*/
PDR06STR	IO_PDR06;
/*__IO_EXTERN*/
PDR07STR	IO_PDR07;
/*__IO_EXTERN*/
PDR08STR	IO_PDR08;
/*__IO_EXTERN*/
PDR09STR	IO_PDR09;
/*__IO_EXTERN*/
PDR10STR	IO_PDR10;
/*__IO_EXTERN*/
PDR11STR	IO_PDR11;
/*__IO_EXTERN*/
PDR12STR	IO_PDR12;
/*__IO_EXTERN*/
PDR13STR	IO_PDR13;
/*__IO_EXTERN*/
PDR14STR	IO_PDR14;
/*__IO_EXTERN*/
PDR15STR	IO_PDR15;
/*__IO_EXTERN*/
PDR16STR	IO_PDR16;
/*__IO_EXTERN*/
PDR17STR	IO_PDR17;
/*__IO_EXTERN*/
PDR18STR	IO_PDR18;
/*__IO_EXTERN*/
PDR19STR	IO_PDR19;
/*__IO_EXTERN*/
WDTECR0STR	IO_WDTECR0;
/*__IO_EXTERN*/
WDTCR0STR	IO_WDTCR0;
/*__IO_EXTERN*/
__BYTE	IO_WDTCPR0;
/*__IO_EXTERN*/
const  WDTCR1STR	IO_WDTCR1;
/*__IO_EXTERN*/
__BYTE	IO_WDTCPR1;
/*__IO_EXTERN*/
DICRSTR	IO_DICR;
/*__IO_EXTERN*/
__HWORD	IO_TMRLRA0;
/*__IO_EXTERN*/
const __HWORD	IO_TMR0;
/*__IO_EXTERN*/
__HWORD	IO_TMRLRB0;
/*__IO_EXTERN*/
TMCSR0STR	IO_TMCSR0;
/*__IO_EXTERN*/
__HWORD	IO_TMRLRA7;
/*__IO_EXTERN*/
const __HWORD	IO_TMR7;
/*__IO_EXTERN*/
__HWORD	IO_TMRLRB7;
/*__IO_EXTERN*/
TMCSR7STR	IO_TMCSR7;
/*__IO_EXTERN*/
FRS8STR	IO_FRS8;
/*__IO_EXTERN*/
FRS9STR	IO_FRS9;
/*__IO_EXTERN*/
OCLS67STR	IO_OCLS67;
/*__IO_EXTERN*/
OCLS89STR	IO_OCLS89;
/*__IO_EXTERN*/
BT0STR	IO_BT0;
/*__IO_EXTERN*/
BT1STR	IO_BT1;
/*__IO_EXTERN*/
BTSEL01STR	IO_BTSEL01;
/*__IO_EXTERN*/
BTSSSRSTR	IO_BTSSSR;
/*__IO_EXTENDED*/
__HWORD	IO_TMRLRA1;
/*__IO_EXTENDED*/
const __HWORD	IO_TMR1;
/*__IO_EXTENDED*/
__HWORD	IO_TMRLRB1;
/*__IO_EXTENDED*/
TMCSR1STR	IO_TMCSR1;
/*__IO_EXTENDED*/
__HWORD	IO_TMRLRA2;
/*__IO_EXTENDED*/
const __HWORD	IO_TMR2;
/*__IO_EXTENDED*/
__HWORD	IO_TMRLRB2;
/*__IO_EXTENDED*/
TMCSR2STR	IO_TMCSR2;
/*__IO_EXTENDED*/
__HWORD	IO_TMRLRA3;
/*__IO_EXTENDED*/
const __HWORD	IO_TMR3;
/*__IO_EXTENDED*/
__HWORD	IO_TMRLRB3;
/*__IO_EXTENDED*/
TMCSR3STR	IO_TMCSR3;
/*__IO_EXTENDED*/
const __WORD	IO_MSCY4;
/*__IO_EXTENDED*/
const __WORD	IO_MSCY5;
/*__IO_EXTENDED*/
__WORD	IO_OCCP6;
/*__IO_EXTENDED*/
__WORD	IO_OCCP7;
/*__IO_EXTENDED*/
OCS67STR	IO_OCS67;
/*__IO_EXTENDED*/
__WORD	IO_OCCP8;
/*__IO_EXTENDED*/
__WORD	IO_OCCP9;
/*__IO_EXTENDED*/
OCS89STR	IO_OCS89;
/*__IO_EXTENDED*/
EPFR64STR	IO_EPFR64;
/*__IO_EXTENDED*/
EPFR65STR	IO_EPFR65;
/*__IO_EXTENDED*/
EPFR66STR	IO_EPFR66;
/*__IO_EXTENDED*/
EPFR67STR	IO_EPFR67;
/*__IO_EXTENDED*/
EPFR68STR	IO_EPFR68;
/*__IO_EXTENDED*/
EPFR69STR	IO_EPFR69;
/*__IO_EXTENDED*/
EPFR70STR	IO_EPFR70;
/*__IO_EXTENDED*/
EPFR71STR	IO_EPFR71;
/*__IO_EXTENDED*/
EPFR72STR	IO_EPFR72;
/*__IO_EXTENDED*/
EPFR73STR	IO_EPFR73;
/*__IO_EXTENDED*/
EPFR74STR	IO_EPFR74;
/*__IO_EXTENDED*/
EPFR75STR	IO_EPFR75;
/*__IO_EXTENDED*/
EPFR76STR	IO_EPFR76;
/*__IO_EXTENDED*/
EPFR77STR	IO_EPFR77;
/*__IO_EXTENDED*/
EPFR78STR	IO_EPFR78;
/*__IO_EXTENDED*/
EPFR79STR	IO_EPFR79;
/*__IO_EXTENDED*/
EPFR80STR	IO_EPFR80;
/*__IO_EXTENDED*/
EPFR81STR	IO_EPFR81;
/*__IO_EXTENDED*/
EPFR82STR	IO_EPFR82;
/*__IO_EXTENDED*/
EPFR83STR	IO_EPFR83;
/*__IO_EXTENDED*/
EPFR84STR	IO_EPFR84;
/*__IO_EXTENDED*/
EPFR85STR	IO_EPFR85;
/*__IO_EXTENDED*/
EPFR86STR	IO_EPFR86;
/*__IO_EXTENDED*/
EPFR87STR	IO_EPFR87;
/*__IO_EXTENDED*/
EPFR88STR	IO_EPFR88;
/*__IO_EXTENDED*/
__HWORD	IO_TMRLRA4;
/*__IO_EXTENDED*/
const __HWORD	IO_TMR4;
/*__IO_EXTENDED*/
__HWORD	IO_TMRLRB4;
/*__IO_EXTENDED*/
TMCSR4STR	IO_TMCSR4;
/*__IO_EXTENDED*/
__HWORD	IO_TMRLRA5;
/*__IO_EXTENDED*/
const __HWORD	IO_TMR5;
/*__IO_EXTENDED*/
__HWORD	IO_TMRLRB5;
/*__IO_EXTENDED*/
TMCSR5STR	IO_TMCSR5;
/*__IO_EXTENDED*/
__HWORD	IO_TMRLRA6;
/*__IO_EXTENDED*/
const __HWORD	IO_TMR6;
/*__IO_EXTENDED*/
__HWORD	IO_TMRLRB6;
/*__IO_EXTENDED*/
TMCSR6STR	IO_TMCSR6;
/*__IO_EXTENDED*/
DACR0STR	IO_DACR0;
/*__IO_EXTENDED*/
__BYTE	IO_DADR0;
/*__IO_EXTENDED*/
DACR1STR	IO_DACR1;
/*__IO_EXTENDED*/
__BYTE	IO_DADR1;
/*__IO_EXTENDED*/
ICSEL0STR	IO_ICSEL0;
/*__IO_EXTENDED*/
ICSEL1STR	IO_ICSEL1;
/*__IO_EXTENDED*/
ICSEL2STR	IO_ICSEL2;
/*__IO_EXTENDED*/
ICSEL3STR	IO_ICSEL3;
/*__IO_EXTENDED*/
ICSEL5STR	IO_ICSEL5;
/*__IO_EXTENDED*/
ICSEL6STR	IO_ICSEL6;
/*__IO_EXTENDED*/
ICSEL7STR	IO_ICSEL7;
/*__IO_EXTENDED*/
ICSEL8STR	IO_ICSEL8;
/*__IO_EXTENDED*/
ICSEL9STR	IO_ICSEL9;
/*__IO_EXTENDED*/
ICSEL10STR	IO_ICSEL10;
/*__IO_EXTENDED*/
ICSEL11STR	IO_ICSEL11;
/*__IO_EXTENDED*/
ICSEL13STR	IO_ICSEL13;
/*__IO_EXTENDED*/
ICSEL14STR	IO_ICSEL14;
/*__IO_EXTENDED*/
ICSEL15STR	IO_ICSEL15;
/*__IO_EXTENDED*/
ICSEL16STR	IO_ICSEL16;
/*__IO_EXTENDED*/
ICSEL17STR	IO_ICSEL17;
/*__IO_EXTENDED*/
ICSEL18STR	IO_ICSEL18;
/*__IO_EXTENDED*/
ICSEL19STR	IO_ICSEL19;
/*__IO_EXTENDED*/
ICSEL20STR	IO_ICSEL20;
/*__IO_EXTENDED*/
ICSEL21STR	IO_ICSEL21;
/*__IO_EXTENDED*/
ICSEL22STR	IO_ICSEL22;
/*__IO_EXTENDED*/
ICSEL23STR	IO_ICSEL23;
/*__IO_EXTENDED*/
const  IRPR0HSTR	IO_IRPR0H;
/*__IO_EXTENDED*/
const  IRPR0LSTR	IO_IRPR0L;
/*__IO_EXTENDED*/
const  IRPR1HSTR	IO_IRPR1H;
/*__IO_EXTENDED*/
const  IRPR1LSTR	IO_IRPR1L;
/*__IO_EXTENDED*/
const  IRPR3HSTR	IO_IRPR3H;
/*__IO_EXTENDED*/
const  IRPR3LSTR	IO_IRPR3L;
/*__IO_EXTENDED*/
const  IRPR4HSTR	IO_IRPR4H;
/*__IO_EXTENDED*/
const  IRPR4LSTR	IO_IRPR4L;
/*__IO_EXTENDED*/
const  IRPR5HSTR	IO_IRPR5H;
/*__IO_EXTENDED*/
const  IRPR5LSTR	IO_IRPR5L;
/*__IO_EXTENDED*/
const  IRPR6HSTR	IO_IRPR6H;
/*__IO_EXTENDED*/
const  IRPR6LSTR	IO_IRPR6L;
/*__IO_EXTENDED*/
const  IRPR7HSTR	IO_IRPR7H;
/*__IO_EXTENDED*/
const  IRPR7LSTR	IO_IRPR7L;
/*__IO_EXTENDED*/
const  IRPR8HSTR	IO_IRPR8H;
/*__IO_EXTENDED*/
const  IRPR8LSTR	IO_IRPR8L;
/*__IO_EXTENDED*/
const  IRPR9HSTR	IO_IRPR9H;
/*__IO_EXTENDED*/
const  IRPR9LSTR	IO_IRPR9L;
/*__IO_EXTENDED*/
const  IRPR10HSTR	IO_IRPR10H;
/*__IO_EXTENDED*/
const  IRPR10LSTR	IO_IRPR10L;
/*__IO_EXTENDED*/
const  IRPR11HSTR	IO_IRPR11H;
/*__IO_EXTENDED*/
const  IRPR11LSTR	IO_IRPR11L;
/*__IO_EXTENDED*/
const  IRPR12HSTR	IO_IRPR12H;
/*__IO_EXTENDED*/
const  IRPR12LSTR	IO_IRPR12L;
/*__IO_EXTENDED*/
const  IRPR13HSTR	IO_IRPR13H;
/*__IO_EXTENDED*/
const  IRPR13LSTR	IO_IRPR13L;
/*__IO_EXTENDED*/
const  IRPR14HSTR	IO_IRPR14H;
/*__IO_EXTENDED*/
const  IRPR14LSTR	IO_IRPR14L;
/*__IO_EXTENDED*/
const  IRPR15HSTR	IO_IRPR15H;
/*__IO_EXTENDED*/
const  IRPR15LSTR	IO_IRPR15L;
/*__IO_EXTENDED*/
ICSEL24STR	IO_ICSEL24;
/*__IO_EXTENDED*/
ICSEL25STR	IO_ICSEL25;
/*__IO_EXTENDED*/
ICSEL26STR	IO_ICSEL26;
/*__IO_EXTENDED*/
ICSEL27STR	IO_ICSEL27;
/*__IO_EXTENDED*/
ICRSTR	IO_ICR[CONSTANT_48];
/*__IO_EXTENDED*/
const  RSTRRSTR	IO_RSTRR;
/*__IO_EXTENDED*/
RSTCRSTR	IO_RSTCR;
/*__IO_EXTENDED*/
STBCRSTR	IO_STBCR;
/*__IO_EXTENDED*/
DIVR0STR	IO_DIVR0;
/*__IO_EXTENDED*/
DIVR1STR	IO_DIVR1;
/*__IO_EXTENDED*/
DIVR2STR	IO_DIVR2;
/*__IO_EXTENDED*/
IORR00STR	IO_IORR00;
/*__IO_EXTENDED*/
IORR01STR	IO_IORR01;
/*__IO_EXTENDED*/
IORR02STR	IO_IORR02;
/*__IO_EXTENDED*/
IORR03STR	IO_IORR03;
/*__IO_EXTENDED*/
IORR04STR	IO_IORR04;
/*__IO_EXTENDED*/
IORR05STR	IO_IORR05;
/*__IO_EXTENDED*/
IORR06STR	IO_IORR06;
/*__IO_EXTENDED*/
IORR07STR	IO_IORR07;
/*__IO_EXTENDED*/
IORR08STR	IO_IORR08;
/*__IO_EXTENDED*/
IORR09STR	IO_IORR09;
/*__IO_EXTENDED*/
IORR10STR	IO_IORR10;
/*__IO_EXTENDED*/
IORR11STR	IO_IORR11;
/*__IO_EXTENDED*/
IORR12STR	IO_IORR12;
/*__IO_EXTENDED*/
IORR13STR	IO_IORR13;
/*__IO_EXTENDED*/
IORR14STR	IO_IORR14;
/*__IO_EXTENDED*/
IORR15STR	IO_IORR15;
/*__IO_EXTENDED*/
CANPRESTR	IO_CANPRE;
/*__IO_EXTENDED*/
CSCFGSTR	IO_CSCFG;
/*__IO_EXTENDED*/
CMCFGSTR	IO_CMCFG;
/*__IO_EXTENDED*/
__HWORD	IO_ADERH0;
/*__IO_EXTENDED*/
__HWORD	IO_ADERL0;
/*__IO_EXTENDED*/
__HWORD	IO_ADERL1;
/*__IO_EXTENDED*/
CUCR0STR	IO_CUCR0;
/*__IO_EXTENDED*/
CUCR1STR	IO_CUCR1;
/*__IO_EXTENDED*/
CPUARSTR	IO_CPUAR;
/*__IO_EXTENDED*/
EIRR0STR	IO_EIRR0;
/*__IO_EXTENDED*/
ENIR0STR	IO_ENIR0;
/*__IO_EXTENDED*/
ELVR0STR	IO_ELVR0;
/*__IO_EXTENDED*/
EIRR1STR	IO_EIRR1;
/*__IO_EXTENDED*/
ENIR1STR	IO_ENIR1;
/*__IO_EXTENDED*/
ELVR1STR	IO_ELVR1;
/*__IO_EXTENDED*/
__HWORD	IO_WTDR;
/*__IO_EXTENDED*/
WTCRHSTR	IO_WTCRH;
/*__IO_EXTENDED*/
WTCRMSTR	IO_WTCRM;
/*__IO_EXTENDED*/
WTCRLSTR	IO_WTCRL;
/*__IO_EXTENDED*/
__BYTE	IO_WTBRH;
/*__IO_EXTENDED*/
__BYTE	IO_WTBRM;
/*__IO_EXTENDED*/
__BYTE	IO_WTBRL;
/*__IO_EXTENDED*/
__BYTE	IO_WTHR;
/*__IO_EXTENDED*/
__BYTE	IO_WTMR;
/*__IO_EXTENDED*/
__BYTE	IO_WTSR;
/*__IO_EXTENDED*/
CSVCRSTR	IO_CSVCR;
/*__IO_EXTENDED*/
REGSELSTR	IO_REGSEL;
/*__IO_EXTENDED*/
LVD5RSTR	IO_LVD5R;
/*__IO_EXTENDED*/
LVD5FSTR	IO_LVD5F;
/*__IO_EXTENDED*/
LVDSTR	IO_LVD;
/*__IO_EXTENDED*/
PMUSTRSTR	IO_PMUSTR;
/*__IO_EXTENDED*/
PMUCTLRSTR	IO_PMUCTLR;
/*__IO_EXTENDED*/
PWRTMCTLSTR	IO_PWRTMCTL;
/*__IO_EXTENDED*/
__BYTE	IO_PMUINTF0;
/*__IO_EXTENDED*/
__BYTE	IO_PMUINTF1;
/*__IO_EXTENDED*/
PMUINTF2STR	IO_PMUINTF2;
/*__IO_EXTENDED*/
ASR0STR	IO_ASR0;
/*__IO_EXTENDED*/
ASR1STR	IO_ASR1;
/*__IO_EXTENDED*/
ASR2STR	IO_ASR2;
/*__IO_EXTENDED*/
ASR3STR	IO_ASR3;
/*__IO_EXTENDED*/
ACR0STR	IO_ACR0;
/*__IO_EXTENDED*/
ACR1STR	IO_ACR1;
/*__IO_EXTENDED*/
ACR2STR	IO_ACR2;
/*__IO_EXTENDED*/
ACR3STR	IO_ACR3;
/*__IO_EXTENDED*/
AWR0STR	IO_AWR0;
/*__IO_EXTENDED*/
AWR1STR	IO_AWR1;
/*__IO_EXTENDED*/
AWR2STR	IO_AWR2;
/*__IO_EXTENDED*/
AWR3STR	IO_AWR3;
/*__IO_EXTENDED*/
BPCCRASTR	IO_BPCCRA;
/*__IO_EXTENDED*/
BPCCRBSTR	IO_BPCCRB;
/*__IO_EXTENDED*/
BPCCRCSTR	IO_BPCCRC;
/*__IO_EXTENDED*/
__WORD	IO_BPCTRA;
/*__IO_EXTENDED*/
__WORD	IO_BPCTRB;
/*__IO_EXTENDED*/
__WORD	IO_BPCTRC;
/*__IO_EXTENDED*/
const __BYTE	IO_BMODR;
/*__IO_EXTENDED*/
FCTLRSTR	IO_FCTLR;
/*__IO_EXTENDED*/
FSTRSTR	IO_FSTR;
/*__IO_EXTENDED*/
__HWORD	IO_WREN;
/*__IO_EXTENDED*/
WRSTR	IO_WR[CONSTANT_16];
/*__IO_EXTENDED*/
__WORD	IO_TPUUNLOCK;
/*__IO_EXTENDED*/
const  TPULSTSTR	IO_TPULST;
/*__IO_EXTENDED*/
TPUVSTSTR	IO_TPUVST;
/*__IO_EXTENDED*/
TPUCFGSTR	IO_TPUCFG;
/*__IO_EXTENDED*/
const __BYTE	IO_TPUTIR;
/*__IO_EXTENDED*/
const __BYTE	IO_TPUTST;
/*__IO_EXTENDED*/
const __BYTE	IO_TPUTIE;
/*__IO_EXTENDED*/
const __WORD	IO_TPUMID;
/*__IO_EXTENDED*/
TPUTCN00STR	IO_TPUTCN00;
/*__IO_EXTENDED*/
TPUTCN01STR	IO_TPUTCN01;
/*__IO_EXTENDED*/
TPUTCN02STR	IO_TPUTCN02;
/*__IO_EXTENDED*/
TPUTCN03STR	IO_TPUTCN03;
/*__IO_EXTENDED*/
TPUTCN04STR	IO_TPUTCN04;
/*__IO_EXTENDED*/
TPUTCN05STR	IO_TPUTCN05;
/*__IO_EXTENDED*/
TPUTCN06STR	IO_TPUTCN06;
/*__IO_EXTENDED*/
TPUTCN07STR	IO_TPUTCN07;
/*__IO_EXTENDED*/
TPUTCN10STR	IO_TPUTCN10;
/*__IO_EXTENDED*/
TPUTCN11STR	IO_TPUTCN11;
/*__IO_EXTENDED*/
TPUTCN12STR	IO_TPUTCN12;
/*__IO_EXTENDED*/
TPUTCN13STR	IO_TPUTCN13;
/*__IO_EXTENDED*/
TPUTCN14STR	IO_TPUTCN14;
/*__IO_EXTENDED*/
TPUTCN15STR	IO_TPUTCN15;
/*__IO_EXTENDED*/
TPUTCN16STR	IO_TPUTCN16;
/*__IO_EXTENDED*/
TPUTCN17STR	IO_TPUTCN17;
/*__IO_EXTENDED*/
const __WORD	IO_TPUTCC0;
/*__IO_EXTENDED*/
const __WORD	IO_TPUTCC1;
/*__IO_EXTENDED*/
const __WORD	IO_TPUTCC2;
/*__IO_EXTENDED*/
const __WORD	IO_TPUTCC3;
/*__IO_EXTENDED*/
const __WORD	IO_TPUTCC4;
/*__IO_EXTENDED*/
const __WORD	IO_TPUTCC5;
/*__IO_EXTENDED*/
const __WORD	IO_TPUTCC6;
/*__IO_EXTENDED*/
const __WORD	IO_TPUTCC7;
/*__IO_EXTENDED*/
__WORD	IO_HSCFR;
/*__IO_EXTENDED*/
MBRSTR	IO_MBR;
/*__IO_EXTENDED*/
__HWORD	IO_UER;
/*__IO_EXTENDED*/
DCCR0STR	IO_DCCR0;
/*__IO_EXTENDED*/
DCSR0STR	IO_DCSR0;
/*__IO_EXTENDED*/
__HWORD	IO_DTCR0;
/*__IO_EXTENDED*/
__WORD	IO_DSAR0;
/*__IO_EXTENDED*/
__WORD	IO_DDAR0;
/*__IO_EXTENDED*/
DCCR1STR	IO_DCCR1;
/*__IO_EXTENDED*/
DCSR1STR	IO_DCSR1;
/*__IO_EXTENDED*/
__HWORD	IO_DTCR1;
/*__IO_EXTENDED*/
__WORD	IO_DSAR1;
/*__IO_EXTENDED*/
__WORD	IO_DDAR1;
/*__IO_EXTENDED*/
DCCR2STR	IO_DCCR2;
/*__IO_EXTENDED*/
DCSR2STR	IO_DCSR2;
/*__IO_EXTENDED*/
__HWORD	IO_DTCR2;
/*__IO_EXTENDED*/
__WORD	IO_DSAR2;
/*__IO_EXTENDED*/
__WORD	IO_DDAR2;
/*__IO_EXTENDED*/
DCCR3STR	IO_DCCR3;
/*__IO_EXTENDED*/
DCSR3STR	IO_DCSR3;
/*__IO_EXTENDED*/
__HWORD	IO_DTCR3;
/*__IO_EXTENDED*/
__WORD	IO_DSAR3;
/*__IO_EXTENDED*/
__WORD	IO_DDAR3;
/*__IO_EXTENDED*/
DCCR4STR	IO_DCCR4;
/*__IO_EXTENDED*/
DCSR4STR	IO_DCSR4;
/*__IO_EXTENDED*/
__HWORD	IO_DTCR4;
/*__IO_EXTENDED*/
__WORD	IO_DSAR4;
/*__IO_EXTENDED*/
__WORD	IO_DDAR4;
/*__IO_EXTENDED*/
DCCR5STR	IO_DCCR5;
/*__IO_EXTENDED*/
DCSR5STR	IO_DCSR5;
/*__IO_EXTENDED*/
__HWORD	IO_DTCR5;
/*__IO_EXTENDED*/
__WORD	IO_DSAR5;
/*__IO_EXTENDED*/
__WORD	IO_DDAR5;
/*__IO_EXTENDED*/
DCCR6STR	IO_DCCR6;
/*__IO_EXTENDED*/
DCSR6STR	IO_DCSR6;
/*__IO_EXTENDED*/
__HWORD	IO_DTCR6;
/*__IO_EXTENDED*/
__WORD	IO_DSAR6;
/*__IO_EXTENDED*/
__WORD	IO_DDAR6;
/*__IO_EXTENDED*/
DCCR7STR	IO_DCCR7;
/*__IO_EXTENDED*/
DCSR7STR	IO_DCSR7;
/*__IO_EXTENDED*/
__HWORD	IO_DTCR7;
/*__IO_EXTENDED*/
__WORD	IO_DSAR7;
/*__IO_EXTENDED*/
__WORD	IO_DDAR7;
/*__IO_EXTENDED*/
DCCR8STR	IO_DCCR8;
/*__IO_EXTENDED*/
DCSR8STR	IO_DCSR8;
/*__IO_EXTENDED*/
__HWORD	IO_DTCR8;
/*__IO_EXTENDED*/
__WORD	IO_DSAR8;
/*__IO_EXTENDED*/
__WORD	IO_DDAR8;
/*__IO_EXTENDED*/
DCCR9STR	IO_DCCR9;
/*__IO_EXTENDED*/
DCSR9STR	IO_DCSR9;
/*__IO_EXTENDED*/
__HWORD	IO_DTCR9;
/*__IO_EXTENDED*/
__WORD	IO_DSAR9;
/*__IO_EXTENDED*/
__WORD	IO_DDAR9;
/*__IO_EXTENDED*/
DCCR10STR	IO_DCCR10;
/*__IO_EXTENDED*/
DCSR10STR	IO_DCSR10;
/*__IO_EXTENDED*/
__HWORD	IO_DTCR10;
/*__IO_EXTENDED*/
__WORD	IO_DSAR10;
/*__IO_EXTENDED*/
__WORD	IO_DDAR10;
/*__IO_EXTENDED*/
DCCR11STR	IO_DCCR11;
/*__IO_EXTENDED*/
DCSR11STR	IO_DCSR11;
/*__IO_EXTENDED*/
__HWORD	IO_DTCR11;
/*__IO_EXTENDED*/
__WORD	IO_DSAR11;
/*__IO_EXTENDED*/
__WORD	IO_DDAR11;
/*__IO_EXTENDED*/
DCCR12STR	IO_DCCR12;
/*__IO_EXTENDED*/
DCSR12STR	IO_DCSR12;
/*__IO_EXTENDED*/
__HWORD	IO_DTCR12;
/*__IO_EXTENDED*/
__WORD	IO_DSAR12;
/*__IO_EXTENDED*/
__WORD	IO_DDAR12;
/*__IO_EXTENDED*/
DCCR13STR	IO_DCCR13;
/*__IO_EXTENDED*/
DCSR13STR	IO_DCSR13;
/*__IO_EXTENDED*/
__HWORD	IO_DTCR13;
/*__IO_EXTENDED*/
__WORD	IO_DSAR13;
/*__IO_EXTENDED*/
__WORD	IO_DDAR13;
/*__IO_EXTENDED*/
DCCR14STR	IO_DCCR14;
/*__IO_EXTENDED*/
DCSR14STR	IO_DCSR14;
/*__IO_EXTENDED*/
__HWORD	IO_DTCR14;
/*__IO_EXTENDED*/
__WORD	IO_DSAR14;
/*__IO_EXTENDED*/
__WORD	IO_DDAR14;
/*__IO_EXTENDED*/
DCCR15STR	IO_DCCR15;
/*__IO_EXTENDED*/
DCSR15STR	IO_DCSR15;
/*__IO_EXTENDED*/
__HWORD	IO_DTCR15;
/*__IO_EXTENDED*/
__WORD	IO_DSAR15;
/*__IO_EXTENDED*/
__WORD	IO_DDAR15;
/*__IO_EXTENDED*/
DNMIRSTR	IO_DNMIR;
/*__IO_EXTENDED*/
DILVRSTR	IO_DILVR;
/*__IO_EXTENDED*/
DMACRSTR	IO_DMACR;
/*__IO_EXTENDED*/
DDR00STR	IO_DDR00;
/*__IO_EXTENDED*/
DDR01STR	IO_DDR01;
/*__IO_EXTENDED*/
DDR02STR	IO_DDR02;
/*__IO_EXTENDED*/
DDR03STR	IO_DDR03;
/*__IO_EXTENDED*/
DDR04STR	IO_DDR04;
/*__IO_EXTENDED*/
DDR05STR	IO_DDR05;
/*__IO_EXTENDED*/
DDR06STR	IO_DDR06;
/*__IO_EXTENDED*/
DDR07STR	IO_DDR07;
/*__IO_EXTENDED*/
DDR08STR	IO_DDR08;
/*__IO_EXTENDED*/
DDR09STR	IO_DDR09;
/*__IO_EXTENDED*/
DDR10STR	IO_DDR10;
/*__IO_EXTENDED*/
DDR11STR	IO_DDR11;
/*__IO_EXTENDED*/
DDR12STR	IO_DDR12;
/*__IO_EXTENDED*/
DDR13STR	IO_DDR13;
/*__IO_EXTENDED*/
DDR14STR	IO_DDR14;
/*__IO_EXTENDED*/
DDR15STR	IO_DDR15;
/*__IO_EXTENDED*/
DDR16STR	IO_DDR16;
/*__IO_EXTENDED*/
DDR17STR	IO_DDR17;
/*__IO_EXTENDED*/
DDR18STR	IO_DDR18;
/*__IO_EXTENDED*/
DDR19STR	IO_DDR19;
/*__IO_EXTENDED*/
PFR00STR	IO_PFR00;
/*__IO_EXTENDED*/
PFR01STR	IO_PFR01;
/*__IO_EXTENDED*/
PFR02STR	IO_PFR02;
/*__IO_EXTENDED*/
PFR03STR	IO_PFR03;
/*__IO_EXTENDED*/
PFR04STR	IO_PFR04;
/*__IO_EXTENDED*/
PFR05STR	IO_PFR05;
/*__IO_EXTENDED*/
PFR06STR	IO_PFR06;
/*__IO_EXTENDED*/
PFR07STR	IO_PFR07;
/*__IO_EXTENDED*/
PFR08STR	IO_PFR08;
/*__IO_EXTENDED*/
PFR09STR	IO_PFR09;
/*__IO_EXTENDED*/
PFR10STR	IO_PFR10;
/*__IO_EXTENDED*/
PFR11STR	IO_PFR11;
/*__IO_EXTENDED*/
PFR12STR	IO_PFR12;
/*__IO_EXTENDED*/
PFR13STR	IO_PFR13;
/*__IO_EXTENDED*/
PFR14STR	IO_PFR14;
/*__IO_EXTENDED*/
PFR15STR	IO_PFR15;
/*__IO_EXTENDED*/
PFR16STR	IO_PFR16;
/*__IO_EXTENDED*/
PFR17STR	IO_PFR17;
/*__IO_EXTENDED*/
PFR18STR	IO_PFR18;
/*__IO_EXTENDED*/
PFR19STR	IO_PFR19;
/*__IO_EXTENDED*/
const  PDDR00STR	IO_PDDR00;
/*__IO_EXTENDED*/
const  PDDR01STR	IO_PDDR01;
/*__IO_EXTENDED*/
const  PDDR02STR	IO_PDDR02;
/*__IO_EXTENDED*/
const  PDDR03STR	IO_PDDR03;
/*__IO_EXTENDED*/
const  PDDR04STR	IO_PDDR04;
/*__IO_EXTENDED*/
const  PDDR05STR	IO_PDDR05;
/*__IO_EXTENDED*/
const  PDDR06STR	IO_PDDR06;
/*__IO_EXTENDED*/
const  PDDR07STR	IO_PDDR07;
/*__IO_EXTENDED*/
const  PDDR08STR	IO_PDDR08;
/*__IO_EXTENDED*/
const  PDDR09STR	IO_PDDR09;
/*__IO_EXTENDED*/
const  PDDR10STR	IO_PDDR10;
/*__IO_EXTENDED*/
const  PDDR11STR	IO_PDDR11;
/*__IO_EXTENDED*/
const  PDDR12STR	IO_PDDR12;
/*__IO_EXTENDED*/
const  PDDR13STR	IO_PDDR13;
/*__IO_EXTENDED*/
const  PDDR14STR	IO_PDDR14;
/*__IO_EXTENDED*/
const  PDDR15STR	IO_PDDR15;
/*__IO_EXTENDED*/
const  PDDR16STR	IO_PDDR16;
/*__IO_EXTENDED*/
const  PDDR17STR	IO_PDDR17;
/*__IO_EXTENDED*/
const  PDDR18STR	IO_PDDR18;
/*__IO_EXTENDED*/
const  PDDR19STR	IO_PDDR19;
/*__IO_EXTENDED*/
EPFR00STR	IO_EPFR00;
/*__IO_EXTENDED*/
EPFR01STR	IO_EPFR01;
/*__IO_EXTENDED*/
EPFR02STR	IO_EPFR02;
/*__IO_EXTENDED*/
EPFR03STR	IO_EPFR03;
/*__IO_EXTENDED*/
EPFR04STR	IO_EPFR04;
/*__IO_EXTENDED*/
EPFR05STR	IO_EPFR05;
/*__IO_EXTENDED*/
EPFR06STR	IO_EPFR06;
/*__IO_EXTENDED*/
EPFR07STR	IO_EPFR07;
/*__IO_EXTENDED*/
EPFR08STR	IO_EPFR08;
/*__IO_EXTENDED*/
EPFR09STR	IO_EPFR09;
/*__IO_EXTENDED*/
EPFR10STR	IO_EPFR10;
/*__IO_EXTENDED*/
EPFR11STR	IO_EPFR11;
/*__IO_EXTENDED*/
EPFR12STR	IO_EPFR12;
/*__IO_EXTENDED*/
EPFR13STR	IO_EPFR13;
/*__IO_EXTENDED*/
EPFR14STR	IO_EPFR14;
/*__IO_EXTENDED*/
EPFR15STR	IO_EPFR15;
/*__IO_EXTENDED*/
EPFR26STR	IO_EPFR26;
/*__IO_EXTENDED*/
EPFR27STR	IO_EPFR27;
/*__IO_EXTENDED*/
EPFR28STR	IO_EPFR28;
/*__IO_EXTENDED*/
EPFR29STR	IO_EPFR29;
/*__IO_EXTENDED*/
EPFR33STR	IO_EPFR33;
/*__IO_EXTENDED*/
EPFR34STR	IO_EPFR34;
/*__IO_EXTENDED*/
EPFR35STR	IO_EPFR35;
/*__IO_EXTENDED*/
EPFR36STR	IO_EPFR36;
/*__IO_EXTENDED*/
EPFR42STR	IO_EPFR42;
/*__IO_EXTENDED*/
EPFR43STR	IO_EPFR43;
/*__IO_EXTENDED*/
EPFR44STR	IO_EPFR44;
/*__IO_EXTENDED*/
EPFR45STR	IO_EPFR45;
/*__IO_EXTENDED*/
EPFR56STR	IO_EPFR56;
/*__IO_EXTENDED*/
EPFR57STR	IO_EPFR57;
/*__IO_EXTENDED*/
EPFR58STR	IO_EPFR58;
/*__IO_EXTENDED*/
EPFR59STR	IO_EPFR59;
/*__IO_EXTENDED*/
EPFR60STR	IO_EPFR60;
/*__IO_EXTENDED*/
EPFR61STR	IO_EPFR61;
/*__IO_EXTENDED*/
EPFR62STR	IO_EPFR62;
/*__IO_EXTENDED*/
EPFR63STR	IO_EPFR63;
/*__IO_EXTENDED*/
PPER00STR	IO_PPER00;
/*__IO_EXTENDED*/
PPER01STR	IO_PPER01;
/*__IO_EXTENDED*/
PPER02STR	IO_PPER02;
/*__IO_EXTENDED*/
PPER03STR	IO_PPER03;
/*__IO_EXTENDED*/
PPER04STR	IO_PPER04;
/*__IO_EXTENDED*/
PPER05STR	IO_PPER05;
/*__IO_EXTENDED*/
PPER06STR	IO_PPER06;
/*__IO_EXTENDED*/
PPER07STR	IO_PPER07;
/*__IO_EXTENDED*/
PPER08STR	IO_PPER08;
/*__IO_EXTENDED*/
PPER09STR	IO_PPER09;
/*__IO_EXTENDED*/
PPER10STR	IO_PPER10;
/*__IO_EXTENDED*/
PPER11STR	IO_PPER11;
/*__IO_EXTENDED*/
PPER12STR	IO_PPER12;
/*__IO_EXTENDED*/
PPER13STR	IO_PPER13;
/*__IO_EXTENDED*/
PPER14STR	IO_PPER14;
/*__IO_EXTENDED*/
PPER15STR	IO_PPER15;
/*__IO_EXTENDED*/
PPER16STR	IO_PPER16;
/*__IO_EXTENDED*/
PPER17STR	IO_PPER17;
/*__IO_EXTENDED*/
PPER18STR	IO_PPER18;
/*__IO_EXTENDED*/
PPER19STR	IO_PPER19;
/*__IO_EXTENDED*/
PORTENSTR	IO_PORTEN;
/*__IO_EXTENDED*/
__HWORD	IO_KEYCDR;
/*__IO_EXTENDED*/
const __WORD	IO_MSCY6;
/*__IO_EXTENDED*/
const __WORD	IO_MSCY7;
/*__IO_EXTENDED*/
CCR0STR	IO_CCR0;
/*__IO_EXTENDED*/
CSR0STR	IO_CSR0;
/*__IO_EXTENDED*/
CCR1STR	IO_CCR1;
/*__IO_EXTENDED*/
CSR1STR	IO_CSR1;
/*__IO_EXTENDED*/
const  MSCH45STR	IO_MSCH45;
/*__IO_EXTENDED*/
MSCL45STR	IO_MSCL45;
/*__IO_EXTENDED*/
const  MSCH67STR	IO_MSCH67;
/*__IO_EXTENDED*/
MSCL67STR	IO_MSCL67;
/*__IO_EXTENDED*/
__WORD	IO_OCCP10;
/*__IO_EXTENDED*/
__WORD	IO_OCCP11;
/*__IO_EXTENDED*/
OCS1011STR	IO_OCS1011;
/*__IO_EXTENDED*/
OCLS1011STR	IO_OCLS1011;
/*__IO_EXTENDED*/
const __WORD	IO_IPCP4;
/*__IO_EXTENDED*/
const __WORD	IO_IPCP5;
/*__IO_EXTENDED*/
LSYNS1STR	IO_LSYNS1;
/*__IO_EXTENDED*/
ICS45STR	IO_ICS45;
/*__IO_EXTENDED*/
const __WORD	IO_IPCP6;
/*__IO_EXTENDED*/
const __WORD	IO_IPCP7;
/*__IO_EXTENDED*/
ICS67STR	IO_ICS67;
/*__IO_EXTENDED*/
const __WORD	IO_IPCP8;
/*__IO_EXTENDED*/
const __WORD	IO_IPCP9;
/*__IO_EXTENDED*/
ICS89STR	IO_ICS89;
/*__IO_EXTENDED*/
const __WORD	IO_MSCY8;
/*__IO_EXTENDED*/
const __WORD	IO_MSCY9;
/*__IO_EXTENDED*/
const  MSCH89STR	IO_MSCH89;
/*__IO_EXTENDED*/
MSCL89STR	IO_MSCL89;
/*__IO_EXTENDED*/
SACRSTR	IO_SACR;
/*__IO_EXTENDED*/
PICDSTR	IO_PICD;
/*__IO_EXTENDED*/
CRCCRSTR	IO_CRCCR;
/*__IO_EXTENDED*/
TCGSSTR	IO_TCGS;
/*__IO_EXTENDED*/
TCGSESTR	IO_TCGSE;
/*__IO_EXTENDED*/
FRS0STR	IO_FRS0;
/*__IO_EXTENDED*/
FRS1STR	IO_FRS1;
/*__IO_EXTENDED*/
FRS2STR	IO_FRS2;
/*__IO_EXTENDED*/
FRS3STR	IO_FRS3;
/*__IO_EXTENDED*/
FRS4STR	IO_FRS4;
/*__IO_EXTENDED*/
__HWORD	IO_OCCP0;
/*__IO_EXTENDED*/
__HWORD	IO_OCCP1;
/*__IO_EXTENDED*/
OCS01STR	IO_OCS01;
/*__IO_EXTENDED*/
OCMOD01STR	IO_OCMOD01;
/*__IO_EXTENDED*/
__HWORD	IO_OCCP2;
/*__IO_EXTENDED*/
__HWORD	IO_OCCP3;
/*__IO_EXTENDED*/
OCS23STR	IO_OCS23;
/*__IO_EXTENDED*/
OCMOD23STR	IO_OCMOD23;
/*__IO_EXTENDED*/
__HWORD	IO_OCCP4;
/*__IO_EXTENDED*/
__HWORD	IO_OCCP5;
/*__IO_EXTENDED*/
OCS45STR	IO_OCS45;
/*__IO_EXTENDED*/
OCMOD45STR	IO_OCMOD45;
/*__IO_EXTENDED*/
const __HWORD	IO_IPCP0;
/*__IO_EXTENDED*/
const __HWORD	IO_IPCP1;
/*__IO_EXTENDED*/
ICS01STR	IO_ICS01;
/*__IO_EXTENDED*/
LSYNSSTR	IO_LSYNS;
/*__IO_EXTENDED*/
const __HWORD	IO_IPCP2;
/*__IO_EXTENDED*/
const __HWORD	IO_IPCP3;
/*__IO_EXTENDED*/
ICS23STR	IO_ICS23;
/*__IO_EXTENDED*/
__HWORD	IO_TMRR0;
/*__IO_EXTENDED*/
__HWORD	IO_TMRR1;
/*__IO_EXTENDED*/
__HWORD	IO_TMRR2;
/*__IO_EXTENDED*/
DTSCR0STR	IO_DTSCR0;
/*__IO_EXTENDED*/
DTSCR1STR	IO_DTSCR1;
/*__IO_EXTENDED*/
DTSCR2STR	IO_DTSCR2;
/*__IO_EXTENDED*/
DTIR0STR	IO_DTIR0;
/*__IO_EXTENDED*/
DTMNS0STR	IO_DTMNS0;
/*__IO_EXTENDED*/
SIGCR10STR	IO_SIGCR10;
/*__IO_EXTENDED*/
SIGCR20STR	IO_SIGCR20;
/*__IO_EXTENDED*/
PICS0STR	IO_PICS0;
/*__IO_EXTENDED*/
FRS5STR	IO_FRS5;
/*__IO_EXTENDED*/
FRS6STR	IO_FRS6;
/*__IO_EXTENDED*/
FRS7STR	IO_FRS7;
/*__IO_EXTENDED*/
ADTSS0STR	IO_ADTSS0;
/*__IO_EXTENDED*/
__WORD	IO_ADTSE0;
/*__IO_EXTENDED*/
__HWORD	IO_ADCOMP0;
/*__IO_EXTENDED*/
__HWORD	IO_ADCOMP1;
/*__IO_EXTENDED*/
__HWORD	IO_ADCOMP2;
/*__IO_EXTENDED*/
__HWORD	IO_ADCOMP3;
/*__IO_EXTENDED*/
__HWORD	IO_ADCOMP4;
/*__IO_EXTENDED*/
__HWORD	IO_ADCOMP5;
/*__IO_EXTENDED*/
__HWORD	IO_ADCOMP6;
/*__IO_EXTENDED*/
__HWORD	IO_ADCOMP7;
/*__IO_EXTENDED*/
__HWORD	IO_ADCOMP8;
/*__IO_EXTENDED*/
__HWORD	IO_ADCOMP9;
/*__IO_EXTENDED*/
__HWORD	IO_ADCOMP10;
/*__IO_EXTENDED*/
__HWORD	IO_ADCOMP11;
/*__IO_EXTENDED*/
__HWORD	IO_ADCOMP12;
/*__IO_EXTENDED*/
__HWORD	IO_ADCOMP13;
/*__IO_EXTENDED*/
__HWORD	IO_ADCOMP14;
/*__IO_EXTENDED*/
__HWORD	IO_ADCOMP15;
/*__IO_EXTENDED*/
__HWORD	IO_ADCOMP16;
/*__IO_EXTENDED*/
__HWORD	IO_ADCOMP17;
/*__IO_EXTENDED*/
__HWORD	IO_ADCOMP18;
/*__IO_EXTENDED*/
__HWORD	IO_ADCOMP19;
/*__IO_EXTENDED*/
__HWORD	IO_ADCOMP20;
/*__IO_EXTENDED*/
__HWORD	IO_ADCOMP21;
/*__IO_EXTENDED*/
__HWORD	IO_ADCOMP22;
/*__IO_EXTENDED*/
__HWORD	IO_ADCOMP23;
/*__IO_EXTENDED*/
__HWORD	IO_ADCOMP24;
/*__IO_EXTENDED*/
__HWORD	IO_ADCOMP25;
/*__IO_EXTENDED*/
__HWORD	IO_ADCOMP26;
/*__IO_EXTENDED*/
__HWORD	IO_ADCOMP27;
/*__IO_EXTENDED*/
__HWORD	IO_ADCOMP28;
/*__IO_EXTENDED*/
__HWORD	IO_ADCOMP29;
/*__IO_EXTENDED*/
__HWORD	IO_ADCOMP30;
/*__IO_EXTENDED*/
__HWORD	IO_ADCOMP31;
/*__IO_EXTENDED*/
ADTCS0STR	IO_ADTCS0;
/*__IO_EXTENDED*/
ADTCS1STR	IO_ADTCS1;
/*__IO_EXTENDED*/
ADTCS2STR	IO_ADTCS2;
/*__IO_EXTENDED*/
ADTCS3STR	IO_ADTCS3;
/*__IO_EXTENDED*/
ADTCS4STR	IO_ADTCS4;
/*__IO_EXTENDED*/
ADTCS5STR	IO_ADTCS5;
/*__IO_EXTENDED*/
ADTCS6STR	IO_ADTCS6;
/*__IO_EXTENDED*/
ADTCS7STR	IO_ADTCS7;
/*__IO_EXTENDED*/
ADTCS8STR	IO_ADTCS8;
/*__IO_EXTENDED*/
ADTCS9STR	IO_ADTCS9;
/*__IO_EXTENDED*/
ADTCS10STR	IO_ADTCS10;
/*__IO_EXTENDED*/
ADTCS11STR	IO_ADTCS11;
/*__IO_EXTENDED*/
ADTCS12STR	IO_ADTCS12;
/*__IO_EXTENDED*/
ADTCS13STR	IO_ADTCS13;
/*__IO_EXTENDED*/
ADTCS14STR	IO_ADTCS14;
/*__IO_EXTENDED*/
ADTCS15STR	IO_ADTCS15;
/*__IO_EXTENDED*/
ADTCS16STR	IO_ADTCS16;
/*__IO_EXTENDED*/
ADTCS17STR	IO_ADTCS17;
/*__IO_EXTENDED*/
ADTCS18STR	IO_ADTCS18;
/*__IO_EXTENDED*/
ADTCS19STR	IO_ADTCS19;
/*__IO_EXTENDED*/
ADTCS20STR	IO_ADTCS20;
/*__IO_EXTENDED*/
ADTCS21STR	IO_ADTCS21;
/*__IO_EXTENDED*/
ADTCS22STR	IO_ADTCS22;
/*__IO_EXTENDED*/
ADTCS23STR	IO_ADTCS23;
/*__IO_EXTENDED*/
ADTCS24STR	IO_ADTCS24;
/*__IO_EXTENDED*/
ADTCS25STR	IO_ADTCS25;
/*__IO_EXTENDED*/
ADTCS26STR	IO_ADTCS26;
/*__IO_EXTENDED*/
ADTCS27STR	IO_ADTCS27;
/*__IO_EXTENDED*/
ADTCS28STR	IO_ADTCS28;
/*__IO_EXTENDED*/
ADTCS29STR	IO_ADTCS29;
/*__IO_EXTENDED*/
ADTCS30STR	IO_ADTCS30;
/*__IO_EXTENDED*/
ADTCS31STR	IO_ADTCS31;
/*__IO_EXTENDED*/
const  ADTCD0STR	IO_ADTCD0;
/*__IO_EXTENDED*/
const  ADTCD1STR	IO_ADTCD1;
/*__IO_EXTENDED*/
const  ADTCD2STR	IO_ADTCD2;
/*__IO_EXTENDED*/
const  ADTCD3STR	IO_ADTCD3;
/*__IO_EXTENDED*/
const  ADTCD4STR	IO_ADTCD4;
/*__IO_EXTENDED*/
const  ADTCD5STR	IO_ADTCD5;
/*__IO_EXTENDED*/
const  ADTCD6STR	IO_ADTCD6;
/*__IO_EXTENDED*/
const  ADTCD7STR	IO_ADTCD7;
/*__IO_EXTENDED*/
const  ADTCD8STR	IO_ADTCD8;
/*__IO_EXTENDED*/
const  ADTCD9STR	IO_ADTCD9;
/*__IO_EXTENDED*/
const  ADTCD10STR	IO_ADTCD10;
/*__IO_EXTENDED*/
const  ADTCD11STR	IO_ADTCD11;
/*__IO_EXTENDED*/
const  ADTCD12STR	IO_ADTCD12;
/*__IO_EXTENDED*/
const  ADTCD13STR	IO_ADTCD13;
/*__IO_EXTENDED*/
const  ADTCD14STR	IO_ADTCD14;
/*__IO_EXTENDED*/
const  ADTCD15STR	IO_ADTCD15;
/*__IO_EXTENDED*/
const  ADTCD16STR	IO_ADTCD16;
/*__IO_EXTENDED*/
const  ADTCD17STR	IO_ADTCD17;
/*__IO_EXTENDED*/
const  ADTCD18STR	IO_ADTCD18;
/*__IO_EXTENDED*/
const  ADTCD19STR	IO_ADTCD19;
/*__IO_EXTENDED*/
const  ADTCD20STR	IO_ADTCD20;
/*__IO_EXTENDED*/
const  ADTCD21STR	IO_ADTCD21;
/*__IO_EXTENDED*/
const  ADTCD22STR	IO_ADTCD22;
/*__IO_EXTENDED*/
const  ADTCD23STR	IO_ADTCD23;
/*__IO_EXTENDED*/
const  ADTCD24STR	IO_ADTCD24;
/*__IO_EXTENDED*/
const  ADTCD25STR	IO_ADTCD25;
/*__IO_EXTENDED*/
const  ADTCD26STR	IO_ADTCD26;
/*__IO_EXTENDED*/
const  ADTCD27STR	IO_ADTCD27;
/*__IO_EXTENDED*/
const  ADTCD28STR	IO_ADTCD28;
/*__IO_EXTENDED*/
const  ADTCD29STR	IO_ADTCD29;
/*__IO_EXTENDED*/
const  ADTCD30STR	IO_ADTCD30;
/*__IO_EXTENDED*/
const  ADTCD31STR	IO_ADTCD31;
/*__IO_EXTENDED*/
ADTECS0STR	IO_ADTECS0;
/*__IO_EXTENDED*/
ADTECS1STR	IO_ADTECS1;
/*__IO_EXTENDED*/
ADTECS2STR	IO_ADTECS2;
/*__IO_EXTENDED*/
ADTECS3STR	IO_ADTECS3;
/*__IO_EXTENDED*/
ADTECS4STR	IO_ADTECS4;
/*__IO_EXTENDED*/
ADTECS5STR	IO_ADTECS5;
/*__IO_EXTENDED*/
ADTECS6STR	IO_ADTECS6;
/*__IO_EXTENDED*/
ADTECS7STR	IO_ADTECS7;
/*__IO_EXTENDED*/
ADTECS8STR	IO_ADTECS8;
/*__IO_EXTENDED*/
ADTECS9STR	IO_ADTECS9;
/*__IO_EXTENDED*/
ADTECS10STR	IO_ADTECS10;
/*__IO_EXTENDED*/
ADTECS11STR	IO_ADTECS11;
/*__IO_EXTENDED*/
ADTECS12STR	IO_ADTECS12;
/*__IO_EXTENDED*/
ADTECS13STR	IO_ADTECS13;
/*__IO_EXTENDED*/
ADTECS14STR	IO_ADTECS14;
/*__IO_EXTENDED*/
ADTECS15STR	IO_ADTECS15;
/*__IO_EXTENDED*/
ADTECS16STR	IO_ADTECS16;
/*__IO_EXTENDED*/
ADTECS17STR	IO_ADTECS17;
/*__IO_EXTENDED*/
ADTECS18STR	IO_ADTECS18;
/*__IO_EXTENDED*/
ADTECS19STR	IO_ADTECS19;
/*__IO_EXTENDED*/
ADTECS20STR	IO_ADTECS20;
/*__IO_EXTENDED*/
ADTECS21STR	IO_ADTECS21;
/*__IO_EXTENDED*/
ADTECS22STR	IO_ADTECS22;
/*__IO_EXTENDED*/
ADTECS23STR	IO_ADTECS23;
/*__IO_EXTENDED*/
ADTECS24STR	IO_ADTECS24;
/*__IO_EXTENDED*/
ADTECS25STR	IO_ADTECS25;
/*__IO_EXTENDED*/
ADTECS26STR	IO_ADTECS26;
/*__IO_EXTENDED*/
ADTECS27STR	IO_ADTECS27;
/*__IO_EXTENDED*/
ADTECS28STR	IO_ADTECS28;
/*__IO_EXTENDED*/
ADTECS29STR	IO_ADTECS29;
/*__IO_EXTENDED*/
ADTECS30STR	IO_ADTECS30;
/*__IO_EXTENDED*/
ADTECS31STR	IO_ADTECS31;
/*__IO_EXTENDED*/
__HWORD	IO_ADRCUT0;
/*__IO_EXTENDED*/
__HWORD	IO_ADRCLT0;
/*__IO_EXTENDED*/
__HWORD	IO_ADRCUT1;
/*__IO_EXTENDED*/
__HWORD	IO_ADRCLT1;
/*__IO_EXTENDED*/
__HWORD	IO_ADRCUT2;
/*__IO_EXTENDED*/
__HWORD	IO_ADRCLT2;
/*__IO_EXTENDED*/
__HWORD	IO_ADRCUT3;
/*__IO_EXTENDED*/
__HWORD	IO_ADRCLT3;
/*__IO_EXTENDED*/
ADRCCS0STR	IO_ADRCCS0;
/*__IO_EXTENDED*/
ADRCCS1STR	IO_ADRCCS1;
/*__IO_EXTENDED*/
ADRCCS2STR	IO_ADRCCS2;
/*__IO_EXTENDED*/
ADRCCS3STR	IO_ADRCCS3;
/*__IO_EXTENDED*/
ADRCCS4STR	IO_ADRCCS4;
/*__IO_EXTENDED*/
ADRCCS5STR	IO_ADRCCS5;
/*__IO_EXTENDED*/
ADRCCS6STR	IO_ADRCCS6;
/*__IO_EXTENDED*/
ADRCCS7STR	IO_ADRCCS7;
/*__IO_EXTENDED*/
ADRCCS8STR	IO_ADRCCS8;
/*__IO_EXTENDED*/
ADRCCS9STR	IO_ADRCCS9;
/*__IO_EXTENDED*/
ADRCCS10STR	IO_ADRCCS10;
/*__IO_EXTENDED*/
ADRCCS11STR	IO_ADRCCS11;
/*__IO_EXTENDED*/
ADRCCS12STR	IO_ADRCCS12;
/*__IO_EXTENDED*/
ADRCCS13STR	IO_ADRCCS13;
/*__IO_EXTENDED*/
ADRCCS14STR	IO_ADRCCS14;
/*__IO_EXTENDED*/
ADRCCS15STR	IO_ADRCCS15;
/*__IO_EXTENDED*/
ADRCCS16STR	IO_ADRCCS16;
/*__IO_EXTENDED*/
ADRCCS17STR	IO_ADRCCS17;
/*__IO_EXTENDED*/
ADRCCS18STR	IO_ADRCCS18;
/*__IO_EXTENDED*/
ADRCCS19STR	IO_ADRCCS19;
/*__IO_EXTENDED*/
ADRCCS20STR	IO_ADRCCS20;
/*__IO_EXTENDED*/
ADRCCS21STR	IO_ADRCCS21;
/*__IO_EXTENDED*/
ADRCCS22STR	IO_ADRCCS22;
/*__IO_EXTENDED*/
ADRCCS23STR	IO_ADRCCS23;
/*__IO_EXTENDED*/
ADRCCS24STR	IO_ADRCCS24;
/*__IO_EXTENDED*/
ADRCCS25STR	IO_ADRCCS25;
/*__IO_EXTENDED*/
ADRCCS26STR	IO_ADRCCS26;
/*__IO_EXTENDED*/
ADRCCS27STR	IO_ADRCCS27;
/*__IO_EXTENDED*/
ADRCCS28STR	IO_ADRCCS28;
/*__IO_EXTENDED*/
ADRCCS29STR	IO_ADRCCS29;
/*__IO_EXTENDED*/
ADRCCS30STR	IO_ADRCCS30;
/*__IO_EXTENDED*/
ADRCCS31STR	IO_ADRCCS31;
/*__IO_EXTENDED*/
const __WORD	IO_ADRCOT0;
/*__IO_EXTENDED*/
__WORD	IO_ADRCIF0;
/*__IO_EXTENDED*/
ADSCANS0STR	IO_ADSCANS0;
/*__IO_EXTENDED*/
ADNCS0STR	IO_ADNCS0;
/*__IO_EXTENDED*/
ADNCS1STR	IO_ADNCS1;
/*__IO_EXTENDED*/
ADNCS2STR	IO_ADNCS2;
/*__IO_EXTENDED*/
ADNCS3STR	IO_ADNCS3;
/*__IO_EXTENDED*/
ADNCS4STR	IO_ADNCS4;
/*__IO_EXTENDED*/
ADNCS5STR	IO_ADNCS5;
/*__IO_EXTENDED*/
ADNCS6STR	IO_ADNCS6;
/*__IO_EXTENDED*/
ADNCS7STR	IO_ADNCS7;
/*__IO_EXTENDED*/
ADNCS8STR	IO_ADNCS8;
/*__IO_EXTENDED*/
ADNCS9STR	IO_ADNCS9;
/*__IO_EXTENDED*/
ADNCS10STR	IO_ADNCS10;
/*__IO_EXTENDED*/
ADNCS11STR	IO_ADNCS11;
/*__IO_EXTENDED*/
ADNCS12STR	IO_ADNCS12;
/*__IO_EXTENDED*/
ADNCS13STR	IO_ADNCS13;
/*__IO_EXTENDED*/
ADNCS14STR	IO_ADNCS14;
/*__IO_EXTENDED*/
ADNCS15STR	IO_ADNCS15;
/*__IO_EXTENDED*/
const __WORD	IO_ADPRTF0;
/*__IO_EXTENDED*/
const __WORD	IO_ADEOCF0;
/*__IO_EXTENDED*/
const  ADCS0STR	IO_ADCS0;
/*__IO_EXTENDED*/
const __BYTE	IO_ADCH0;
/*__IO_EXTENDED*/
ADMD0STR	IO_ADMD0;
/*__IO_EXTENDED*/
ADSTPCS0STR	IO_ADSTPCS0;
/*__IO_EXTENDED*/
ADSTPCS1STR	IO_ADSTPCS1;
/*__IO_EXTENDED*/
ADSTPCS2STR	IO_ADSTPCS2;
/*__IO_EXTENDED*/
ADSTPCS3STR	IO_ADSTPCS3;
/*__IO_EXTENDED*/
ADSTPCS4STR	IO_ADSTPCS4;
/*__IO_EXTENDED*/
ADSTPCS5STR	IO_ADSTPCS5;
/*__IO_EXTENDED*/
ADSTPCS6STR	IO_ADSTPCS6;
/*__IO_EXTENDED*/
ADSTPCS7STR	IO_ADSTPCS7;
/*__IO_EXTENDED*/
ADTSS1STR	IO_ADTSS1;
/*__IO_EXTENDED*/
__WORD	IO_ADTSE1;
/*__IO_EXTENDED*/
__HWORD	IO_ADCOMP32;
/*__IO_EXTENDED*/
__HWORD	IO_ADCOMP33;
/*__IO_EXTENDED*/
__HWORD	IO_ADCOMP34;
/*__IO_EXTENDED*/
__HWORD	IO_ADCOMP35;
/*__IO_EXTENDED*/
__HWORD	IO_ADCOMP36;
/*__IO_EXTENDED*/
__HWORD	IO_ADCOMP37;
/*__IO_EXTENDED*/
__HWORD	IO_ADCOMP38;
/*__IO_EXTENDED*/
__HWORD	IO_ADCOMP39;
/*__IO_EXTENDED*/
__HWORD	IO_ADCOMP40;
/*__IO_EXTENDED*/
__HWORD	IO_ADCOMP41;
/*__IO_EXTENDED*/
__HWORD	IO_ADCOMP42;
/*__IO_EXTENDED*/
__HWORD	IO_ADCOMP43;
/*__IO_EXTENDED*/
__HWORD	IO_ADCOMP44;
/*__IO_EXTENDED*/
__HWORD	IO_ADCOMP45;
/*__IO_EXTENDED*/
__HWORD	IO_ADCOMP46;
/*__IO_EXTENDED*/
__HWORD	IO_ADCOMP47;
/*__IO_EXTENDED*/
ADTCS32STR	IO_ADTCS32;
/*__IO_EXTENDED*/
ADTCS33STR	IO_ADTCS33;
/*__IO_EXTENDED*/
ADTCS34STR	IO_ADTCS34;
/*__IO_EXTENDED*/
ADTCS35STR	IO_ADTCS35;
/*__IO_EXTENDED*/
ADTCS36STR	IO_ADTCS36;
/*__IO_EXTENDED*/
ADTCS37STR	IO_ADTCS37;
/*__IO_EXTENDED*/
ADTCS38STR	IO_ADTCS38;
/*__IO_EXTENDED*/
ADTCS39STR	IO_ADTCS39;
/*__IO_EXTENDED*/
ADTCS40STR	IO_ADTCS40;
/*__IO_EXTENDED*/
ADTCS41STR	IO_ADTCS41;
/*__IO_EXTENDED*/
ADTCS42STR	IO_ADTCS42;
/*__IO_EXTENDED*/
ADTCS43STR	IO_ADTCS43;
/*__IO_EXTENDED*/
ADTCS44STR	IO_ADTCS44;
/*__IO_EXTENDED*/
ADTCS45STR	IO_ADTCS45;
/*__IO_EXTENDED*/
ADTCS46STR	IO_ADTCS46;
/*__IO_EXTENDED*/
ADTCS47STR	IO_ADTCS47;
/*__IO_EXTENDED*/
const  ADTCD32STR	IO_ADTCD32;
/*__IO_EXTENDED*/
const  ADTCD33STR	IO_ADTCD33;
/*__IO_EXTENDED*/
const  ADTCD34STR	IO_ADTCD34;
/*__IO_EXTENDED*/
const  ADTCD35STR	IO_ADTCD35;
/*__IO_EXTENDED*/
const  ADTCD36STR	IO_ADTCD36;
/*__IO_EXTENDED*/
const  ADTCD37STR	IO_ADTCD37;
/*__IO_EXTENDED*/
const  ADTCD38STR	IO_ADTCD38;
/*__IO_EXTENDED*/
const  ADTCD39STR	IO_ADTCD39;
/*__IO_EXTENDED*/
const  ADTCD40STR	IO_ADTCD40;
/*__IO_EXTENDED*/
const  ADTCD41STR	IO_ADTCD41;
/*__IO_EXTENDED*/
const  ADTCD42STR	IO_ADTCD42;
/*__IO_EXTENDED*/
const  ADTCD43STR	IO_ADTCD43;
/*__IO_EXTENDED*/
const  ADTCD44STR	IO_ADTCD44;
/*__IO_EXTENDED*/
const  ADTCD45STR	IO_ADTCD45;
/*__IO_EXTENDED*/
const  ADTCD46STR	IO_ADTCD46;
/*__IO_EXTENDED*/
const  ADTCD47STR	IO_ADTCD47;
/*__IO_EXTENDED*/
ADTECS32STR	IO_ADTECS32;
/*__IO_EXTENDED*/
ADTECS33STR	IO_ADTECS33;
/*__IO_EXTENDED*/
ADTECS34STR	IO_ADTECS34;
/*__IO_EXTENDED*/
ADTECS35STR	IO_ADTECS35;
/*__IO_EXTENDED*/
ADTECS36STR	IO_ADTECS36;
/*__IO_EXTENDED*/
ADTECS37STR	IO_ADTECS37;
/*__IO_EXTENDED*/
ADTECS38STR	IO_ADTECS38;
/*__IO_EXTENDED*/
ADTECS39STR	IO_ADTECS39;
/*__IO_EXTENDED*/
ADTECS40STR	IO_ADTECS40;
/*__IO_EXTENDED*/
ADTECS41STR	IO_ADTECS41;
/*__IO_EXTENDED*/
ADTECS42STR	IO_ADTECS42;
/*__IO_EXTENDED*/
ADTECS43STR	IO_ADTECS43;
/*__IO_EXTENDED*/
ADTECS44STR	IO_ADTECS44;
/*__IO_EXTENDED*/
ADTECS45STR	IO_ADTECS45;
/*__IO_EXTENDED*/
ADTECS46STR	IO_ADTECS46;
/*__IO_EXTENDED*/
ADTECS47STR	IO_ADTECS47;
/*__IO_EXTENDED*/
__HWORD	IO_ADRCUT4;
/*__IO_EXTENDED*/
__HWORD	IO_ADRCLT4;
/*__IO_EXTENDED*/
__HWORD	IO_ADRCUT5;
/*__IO_EXTENDED*/
__HWORD	IO_ADRCLT5;
/*__IO_EXTENDED*/
__HWORD	IO_ADRCUT6;
/*__IO_EXTENDED*/
__HWORD	IO_ADRCLT6;
/*__IO_EXTENDED*/
__HWORD	IO_ADRCUT7;
/*__IO_EXTENDED*/
__HWORD	IO_ADRCLT7;
/*__IO_EXTENDED*/
ADRCCS32STR	IO_ADRCCS32;
/*__IO_EXTENDED*/
ADRCCS33STR	IO_ADRCCS33;
/*__IO_EXTENDED*/
ADRCCS34STR	IO_ADRCCS34;
/*__IO_EXTENDED*/
ADRCCS35STR	IO_ADRCCS35;
/*__IO_EXTENDED*/
ADRCCS36STR	IO_ADRCCS36;
/*__IO_EXTENDED*/
ADRCCS37STR	IO_ADRCCS37;
/*__IO_EXTENDED*/
ADRCCS38STR	IO_ADRCCS38;
/*__IO_EXTENDED*/
ADRCCS39STR	IO_ADRCCS39;
/*__IO_EXTENDED*/
ADRCCS40STR	IO_ADRCCS40;
/*__IO_EXTENDED*/
ADRCCS41STR	IO_ADRCCS41;
/*__IO_EXTENDED*/
ADRCCS42STR	IO_ADRCCS42;
/*__IO_EXTENDED*/
ADRCCS43STR	IO_ADRCCS43;
/*__IO_EXTENDED*/
ADRCCS44STR	IO_ADRCCS44;
/*__IO_EXTENDED*/
ADRCCS45STR	IO_ADRCCS45;
/*__IO_EXTENDED*/
ADRCCS46STR	IO_ADRCCS46;
/*__IO_EXTENDED*/
ADRCCS47STR	IO_ADRCCS47;
/*__IO_EXTENDED*/
const __WORD	IO_ADRCOT1;
/*__IO_EXTENDED*/
__WORD	IO_ADRCIF1;
/*__IO_EXTENDED*/
ADSCANS1STR	IO_ADSCANS1;
/*__IO_EXTENDED*/
ADNCS16STR	IO_ADNCS16;
/*__IO_EXTENDED*/
ADNCS17STR	IO_ADNCS17;
/*__IO_EXTENDED*/
ADNCS18STR	IO_ADNCS18;
/*__IO_EXTENDED*/
ADNCS19STR	IO_ADNCS19;
/*__IO_EXTENDED*/
ADNCS20STR	IO_ADNCS20;
/*__IO_EXTENDED*/
ADNCS21STR	IO_ADNCS21;
/*__IO_EXTENDED*/
ADNCS22STR	IO_ADNCS22;
/*__IO_EXTENDED*/
ADNCS23STR	IO_ADNCS23;
/*__IO_EXTENDED*/
const __WORD	IO_ADPRTF1;
/*__IO_EXTENDED*/
const __WORD	IO_ADEOCF1;
/*__IO_EXTENDED*/
const  ADCS1STR	IO_ADCS1;
/*__IO_EXTENDED*/
const __BYTE	IO_ADCH1;
/*__IO_EXTENDED*/
ADMD1STR	IO_ADMD1;
/*__IO_EXTENDED*/
ADSTPCS8STR	IO_ADSTPCS8;
/*__IO_EXTENDED*/
ADSTPCS9STR	IO_ADSTPCS9;
/*__IO_EXTENDED*/
ADSTPCS10STR	IO_ADSTPCS10;
/*__IO_EXTENDED*/
ADSTPCS11STR	IO_ADSTPCS11;
/*__IO_EXTENDED*/
MFSSTR	IO_MFS0;
/*__IO_EXTENDED*/
MFSSTR	IO_MFS1;
/*__IO_EXTENDED*/
MFSSTR	IO_MFS2;
/*__IO_EXTENDED*/
MFSSTR	IO_MFS3;
/*__IO_EXTENDED*/
MFSSTR	IO_MFS4;
/*__IO_EXTENDED*/
MFSSTR	IO_MFS5;
/*__IO_EXTENDED*/
MFSSTR	IO_MFS6;
/*__IO_EXTENDED*/
MFSSTR	IO_MFS7;
/*__IO_EXTENDED*/
MFSSTR	IO_MFS8;
/*__IO_EXTENDED*/
MFSSTR	IO_MFS9;
/*__IO_EXTENDED*/
MFSSTR	IO_MFS10;
/*__IO_EXTENDED*/
MFSSTR	IO_MFS11;
/*__IO_EXTENDED*/
GATEC0STR	IO_GATEC0;
/*__IO_EXTENDED*/
GATEC2STR	IO_GATEC2;
/*__IO_EXTENDED*/
GATEC4STR	IO_GATEC4;
/*__IO_EXTENDED*/
GTRS0STR	IO_GTRS0;
/*__IO_EXTENDED*/
GTRS1STR	IO_GTRS1;
/*__IO_EXTENDED*/
GTRS2STR	IO_GTRS2;
/*__IO_EXTENDED*/
GTRS3STR	IO_GTRS3;
/*__IO_EXTENDED*/
GTRS4STR	IO_GTRS4;
/*__IO_EXTENDED*/
GTRS5STR	IO_GTRS5;
/*__IO_EXTENDED*/
GTRS6STR	IO_GTRS6;
/*__IO_EXTENDED*/
GTRS7STR	IO_GTRS7;
/*__IO_EXTENDED*/
GTRS8STR	IO_GTRS8;
/*__IO_EXTENDED*/
GTRS9STR	IO_GTRS9;
/*__IO_EXTENDED*/
GTRS10STR	IO_GTRS10;
/*__IO_EXTENDED*/
GTRS11STR	IO_GTRS11;
/*__IO_EXTENDED*/
GTRS12STR	IO_GTRS12;
/*__IO_EXTENDED*/
GTRS13STR	IO_GTRS13;
/*__IO_EXTENDED*/
GTRS14STR	IO_GTRS14;
/*__IO_EXTENDED*/
GTRS15STR	IO_GTRS15;
/*__IO_EXTENDED*/
GTRS16STR	IO_GTRS16;
/*__IO_EXTENDED*/
GTRS17STR	IO_GTRS17;
/*__IO_EXTENDED*/
GTRS18STR	IO_GTRS18;
/*__IO_EXTENDED*/
GTRS19STR	IO_GTRS19;
/*__IO_EXTENDED*/
GTRS20STR	IO_GTRS20;
/*__IO_EXTENDED*/
GTRS21STR	IO_GTRS21;
/*__IO_EXTENDED*/
GTRS22STR	IO_GTRS22;
/*__IO_EXTENDED*/
GTRS23STR	IO_GTRS23;
/*__IO_EXTENDED*/
__HWORD	IO_GTREN0;
/*__IO_EXTENDED*/
__HWORD	IO_GTREN1;
/*__IO_EXTENDED*/
__HWORD	IO_GTREN2;
/*__IO_EXTENDED*/
PPGASTR	IO_PPG0;
/*__IO_EXTENDED*/
PPGASTR	IO_PPG1;
/*__IO_EXTENDED*/
PPGASTR	IO_PPG2;
/*__IO_EXTENDED*/
PPGASTR	IO_PPG3;
/*__IO_EXTENDED*/
PPGBSTR	IO_PPG4;
/*__IO_EXTENDED*/
PPGBSTR	IO_PPG5;
/*__IO_EXTENDED*/
PPGBSTR	IO_PPG6;
/*__IO_EXTENDED*/
PPGBSTR	IO_PPG7;
/*__IO_EXTENDED*/
PPGBSTR	IO_PPG8;
/*__IO_EXTENDED*/
PPGBSTR	IO_PPG9;
/*__IO_EXTENDED*/
PPGBSTR	IO_PPG10;
/*__IO_EXTENDED*/
PPGBSTR	IO_PPG11;
/*__IO_EXTENDED*/
PPGBSTR	IO_PPG12;
/*__IO_EXTENDED*/
PPGBSTR	IO_PPG13;
/*__IO_EXTENDED*/
PPGBSTR	IO_PPG14;
/*__IO_EXTENDED*/
PPGBSTR	IO_PPG15;
/*__IO_EXTENDED*/
PPGBSTR	IO_PPG16;
/*__IO_EXTENDED*/
PPGBSTR	IO_PPG17;
/*__IO_EXTENDED*/
PPGBSTR	IO_PPG18;
/*__IO_EXTENDED*/
PPGBSTR	IO_PPG19;
/*__IO_EXTENDED*/
PPGBSTR	IO_PPG20;
/*__IO_EXTENDED*/
PPGBSTR	IO_PPG21;
/*__IO_EXTENDED*/
PPGBSTR	IO_PPG22;
/*__IO_EXTENDED*/
PPGBSTR	IO_PPG23;
/*__IO_EXTENDED*/
PPGBSTR	IO_PPG24;
/*__IO_EXTENDED*/
PPGBSTR	IO_PPG25;
/*__IO_EXTENDED*/
PPGBSTR	IO_PPG26;
/*__IO_EXTENDED*/
PPGBSTR	IO_PPG27;
/*__IO_EXTENDED*/
PPGBSTR	IO_PPG28;
/*__IO_EXTENDED*/
PPGBSTR	IO_PPG29;
/*__IO_EXTENDED*/
PPGBSTR	IO_PPG30;
/*__IO_EXTENDED*/
PPGBSTR	IO_PPG31;
/*__IO_EXTENDED*/
PPGBSTR	IO_PPG32;
/*__IO_EXTENDED*/
PPGBSTR	IO_PPG33;
/*__IO_EXTENDED*/
PPGBSTR	IO_PPG34;
/*__IO_EXTENDED*/
PPGBSTR	IO_PPG35;
/*__IO_EXTENDED*/
PPGBSTR	IO_PPG36;
/*__IO_EXTENDED*/
PPGBSTR	IO_PPG37;
/*__IO_EXTENDED*/
PPGBSTR	IO_PPG38;
/*__IO_EXTENDED*/
PPGBSTR	IO_PPG39;
/*__IO_EXTENDED*/
PPGBSTR	IO_PPG40;
/*__IO_EXTENDED*/
PPGBSTR	IO_PPG41;
/*__IO_EXTENDED*/
PPGBSTR	IO_PPG42;
/*__IO_EXTENDED*/
PPGBSTR	IO_PPG43;
/*__IO_EXTENDED*/
PPGBSTR	IO_PPG44;
/*__IO_EXTENDED*/
PPGBSTR	IO_PPG45;
/*__IO_EXTENDED*/
PPGBSTR	IO_PPG46;
/*__IO_EXTENDED*/
PPGBSTR	IO_PPG47;
/*__IO_EXTENDED*/
CANSTR	IO_CAN0;
/*__IO_EXTENDED*/
CANSTR	IO_CAN1;
/*__IO_EXTENDED*/
CANSTR	IO_CAN2;
/*__IO_EXTENDED*/
DFCTLRSTR	IO_DFCTLR;
/*__IO_EXTENDED*/
DFSTRSTR	IO_DFSTR;
/*__IO_EXTENDED*/
FLIFCTLRSTR	IO_FLIFCTLR;
/*__IO_EXTENDED*/
__BYTE	IO_FLIFFER1;
/*__IO_EXTENDED*/
__BYTE	IO_FLIFFER2;
/*__IO_EXTENDED*/
SEEARXSTR	IO_SEEARX;
/*__IO_EXTENDED*/
DEEARXSTR	IO_DEEARX;
/*__IO_EXTENDED*/
EECSRXSTR	IO_EECSRX;
/*__IO_EXTENDED*/
EFEARXSTR	IO_EFEARX;
/*__IO_EXTENDED*/
EFECRXSTR	IO_EFECRX;
/*__IO_EXTENDED*/
SEEARASTR	IO_SEEARA;
/*__IO_EXTENDED*/
DEEARASTR	IO_DEEARA;
/*__IO_EXTENDED*/
EECSRASTR	IO_EECSRA;
/*__IO_EXTENDED*/
EFEARASTR	IO_EFEARA;
/*__IO_EXTENDED*/
EFECRASTR	IO_EFECRA;
/*__IO_EXTENDED*/
const  TEAR0XSTR	IO_TEAR0X;
/*__IO_EXTENDED*/
const  TEAR1XSTR	IO_TEAR1X;
/*__IO_EXTENDED*/
const  TEAR2XSTR	IO_TEAR2X;
/*__IO_EXTENDED*/
__HWORD	IO_TAEARX;
/*__IO_EXTENDED*/
__HWORD	IO_TASARX;
/*__IO_EXTENDED*/
TFECRXSTR	IO_TFECRX;
/*__IO_EXTENDED*/
TICRXSTR	IO_TICRX;
/*__IO_EXTENDED*/
TTCRXSTR	IO_TTCRX;
/*__IO_EXTENDED*/
TSRCRXSTR	IO_TSRCRX;
/*__IO_EXTENDED*/
TKCCRXSTR	IO_TKCCRX;
/*__IO_EXTENDED*/
const  TEAR0ASTR	IO_TEAR0A;
/*__IO_EXTENDED*/
const  TEAR1ASTR	IO_TEAR1A;
/*__IO_EXTENDED*/
const  TEAR2ASTR	IO_TEAR2A;
/*__IO_EXTENDED*/
__HWORD	IO_TAEARA;
/*__IO_EXTENDED*/
__HWORD	IO_TASARA;
/*__IO_EXTENDED*/
TFECRASTR	IO_TFECRA;
/*__IO_EXTENDED*/
TICRASTR	IO_TICRA;
/*__IO_EXTENDED*/
TTCRASTR	IO_TTCRA;
/*__IO_EXTENDED*/
TSRCRASTR	IO_TSRCRA;
/*__IO_EXTENDED*/
TKCCRASTR	IO_TKCCRA;
/*__IO_EXTENDED*/
BUSDIGSR0STR	IO_BUSDIGSR0;
/*__IO_EXTENDED*/
BUSDIGSR1STR	IO_BUSDIGSR1;
/*__IO_EXTENDED*/
BUSDIGSR2STR	IO_BUSDIGSR2;
/*__IO_EXTENDED*/
BUSTSTR0STR	IO_BUSTSTR0;
/*__IO_EXTENDED*/
const __WORD	IO_BUSADR0;
/*__IO_EXTENDED*/
const __WORD	IO_BUSADR1;
/*__IO_EXTENDED*/
const __WORD	IO_BUSADR2;
/*__IO_EXTENDED*/
BUSDIGSR3STR	IO_BUSDIGSR3;
/*__IO_EXTENDED*/
BUSDIGSR4STR	IO_BUSDIGSR4;
/*__IO_EXTENDED*/
BUSTSTR1STR	IO_BUSTSTR1;
/*__IO_EXTENDED*/
const __WORD	IO_BUSADR3;
/*__IO_EXTENDED*/
const __WORD	IO_BUSADR4;
/*__IO_EXTENDED*/
__HWORD	IO_DSUCR;
/*__IO_EXTENDED*/
__WORD	IO_PCSR;
/*__IO_EXTENDED*/
__WORD	IO_PSSR;
/*__IO_EXTENDED*/
const __WORD	IO_EDIR1;
/*__IO_EXTENDED*/
const __WORD	IO_EDIR0;

/*__IO_EXTENDED*/
IO_FT1_STR	IO_FT1;
/*__IO_EXTENDED*/
IO_FT2_STR	IO_FT2;
/*__IO_EXTENDED*/
IO_FT3_STR	IO_FT3;
/*__IO_EXTENDED*/
IO_FT4_STR	IO_FT4;
/*__IO_EXTENDED*/
IO_FT0_STR	IO_FT0;
